# Generated by Django 3.1.2 on 2020-11-12 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stckmgt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='recieved_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='opening_stck',
            field=models.IntegerField(default=0, verbose_name='Quantity in Store'),
        ),
    ]
