# Generated by Django 3.1.2 on 2020-11-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stckmgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_no',
            field=models.CharField(max_length=50),
        ),
    ]
