# Generated by Django 3.1.2 on 2020-11-12 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stckmgt', '0002_auto_20201113_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='phone_number',
        ),
    ]
