# Generated by Django 3.1.2 on 2020-11-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stckmgt', '0002_auto_20201111_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
