# Generated by Django 3.1.2 on 2020-11-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stckmgt', '0003_auto_20201112_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='closing_stck',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='opening_stck',
            field=models.IntegerField(default=0),
        ),
    ]
