# Generated by Django 3.1.2 on 2020-11-12 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stckmgt', '0004_auto_20201113_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='recieved_date',
        ),
    ]
