# Generated by Django 3.1.2 on 2020-11-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stckmgt', '0004_auto_20201112_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity MTS'),
        ),
    ]
