# Generated by Django 3.1.2 on 2020-11-12 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stckmgt', '0005_auto_20201112_0533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='issue_by',
            new_name='issued_by',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='issue_to',
            new_name='issued_to',
        ),
    ]
