# Generated by Django 3.1.2 on 2020-11-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stckmgt', '0006_auto_20201112_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='issued_to',
            field=models.CharField(max_length=50, verbose_name='Issued to'),
        ),
    ]
