# Generated by Django 3.1.2 on 2020-11-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stckmgt', '0007_auto_20201112_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
