# Generated by Django 3.1.2 on 2020-11-12 03:40

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stckmgt', '0008_auto_20201112_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='issued_by',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
