# Generated by Django 3.1.2 on 2020-11-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stckmgt', '0009_auto_20201112_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='issued_to',
            field=models.CharField(blank=True, max_length=50, verbose_name='Issued to'),
        ),
    ]
