# Generated by Django 3.1.2 on 2020-11-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stckmgt', '0010_auto_20201112_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='color',
            field=models.CharField(max_length=55),
        ),
    ]
