# Generated by Django 3.1.2 on 2020-11-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stckmgt', '0012_auto_20201112_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='color',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_no',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
